theme: jekyll-theme-slate
title: Stephen Usselman
description: Software Developer • Backend Services • System Design • AI Integration

collections:
  projects:
    output: true
    permalink: /projects/:name/
